---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: bggapp-deploy
   labels:
      app: bgg
      tier: backend
spec:
   replicas: 3
   selector:
      matchLabels: 
         app: bgg
         tier: backend
   minReadySeconds: 5
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 25%
         maxUnavailable: 25%
   template:
      metadata:
         name: bggapp-pod
         labels:
            app: bgg
            tier: backend
      spec:
         containers:
         - name: bggapp-container
           #image: stackupiss/bgg-backend:v1
           image: stackupiss/bgg-backend:v2
           envFrom:
           - configMapRef:
              name: bgg-cm
           - secretRef:
              name: bgg-secret
           ports:
           - containerPort: 3000
           livenessProbe:
              httpGet:
                 path: /healthz
                 port: 3000

---
apiVersion: v1
kind: Service
metadata:
   name: bggapp-svc
   labels:
      app: bgg
      tier: backend
spec:
   type: ClusterIP
   selector:
      app: bgg
      tier: backend
   ports:
   - port: 8080
     targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata: 
   name: bggapp-ing 
   labels:
      app: bgg
      tier: backend
   annotations:
      nginx.ingress.kubernetes.io/limit-rps: "5"
spec: 
   ingressClassName: nginx 
   rules: 
   - host: bgg-144.126.243.70.nip.io
     http: 
         paths:
         - path: / 
           pathType: Prefix 
           backend: 
               service:
                  name: bggapp-svc 
                  port: 
                     number: 8080
