---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
  labels:
    app: dov
data:
  hash_value: '12345'
  hosts: |
    127.0.0.1	localhost
    127.0.1.1	batcomputer

    # The following lines are desirable for IPv6 capable hosts
    ::1     ip6-localhost ip6-loopback
    fe00::0 ip6-localnet
    ff00::0 ip6-mcastprefix
    ff02::1 ip6-allnodes
    ff02::2 ip6-allrouters

  abc: |
   ### this is a file
   one 
   two
   three

  dov-bear.yaml: |
   ---
   apiVersion: v1
   kind: ConfigMap
   metadata:
     name: dov-cm
     labels:
       app: dov-bear
   data:
     INSTANCE_NAME: dov-bear
   
   ---
   apiVersion: apps/v1
   kind: Deployment 
   metadata:
     name: dov-deploy
     labels:
       app: dov-bear
   spec:
     replicas: 2
     selector: 
       matchLabels:
         name: dov-pod
     template:
       metadata:
         name: dov-pod
         labels:
           app: dov-bear
           name: dov-pod
       spec:
         volumes:
         - name: config-vol
           configMap:
              name: myconfig
         containers:
         - name: dov-container
           image: stackupiss/dov-bear:v2 
           imagePullPolicy: IfNotPresent
           ports: 
           - name: dov-port 
             containerPort: 3000
           env: 
           - name: INSTANCE_HASH
             valueFrom:
               fieldRef:
                 fieldPath: status.podIP
           envFrom:
           - configMapRef:
               name: dov-cm
           volumeMounts:
           - name: config-vol
             mountPath: /config
   
   ---
   apiVersion: v1
   kind: Service
   metadata:
      name: dov-svc
      labels:
         app: dov-bear
   spec:
      type: LoadBalancer
      selector:
         app: dov-bear
         name: dov-pod
      ports:
      - name: dov-svc-port 
        port: 8080
        targetPort: dov-port
   
   
