apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./nwapp.yaml
- ./nwdb.yaml

commonLabels:
  env: test
  dept: eng

namePrefix: test-
nameSuffix: -v1
namespace: testns

replicas: 
- name: nwapp 
  count: 2

images:
- name: stackupiss/northwind-app 
  newName: chukmunnlee/northwind-app
  newTag: v2

configMapGenerator:
- name: nwapp-cm 
  literals:
  - DB_USER="fred"
  - DB_PASSWORD="fredfred"
  - LOG_LEVEL="info"

patchesStrategicMerge:
- ./patch.yaml

replacements:
- source:
    name: nwdb
    kind: Service
    fieldPath: metadata.name
  targets:
  - select: 
      name: nwapp 
      kind: Deployment
    fieldPaths:
    - spec.template.spec.containers.[name=northwind-app].env.[name=DB_HOST].value