---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nwapp
  name: nwapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nwapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nwapp
    spec:
      containers:
      - image: stackupiss/northwind-app:v1
        name: nortwind-app
        env:
        - name: DB_HOST
          value: bggdb-cluster-mysql-master
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: changeit
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
             fieldRef:
                fieldPath: metadata.name
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nwapp
  name: nwapp
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nwapp
  type: ClusterIP
