---
apiVersion: v1
kind: Secret
metadata:
  name: nwdb-secret
  labels:
    app: bgg 
type: Opaque
data:
  ROOT_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: nwdb-cluster
  labels:
    app: bgg
spec:
  replicas: 2
  secretName: nwdb-secret 
  image: chukmunnlee/bgg-database:v3.1
