apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: nwapp 
spec:
  template:
    spec:
      containers:
      - name: northwind-app
        resources:
          requests:
            cpu: 256m
            memory: 500Mi
          limits:
            cpu: 512m
            memory: 1Gi